#!/bin/bash
#Menu
clear
echo -e ""
echo -e "=============================-Menu-============================="
echo -e "* menu         : List of Main Commands"
echo -e ""
echo -e "=========================-SSH & OpenVPN-========================"
echo -e "* usernew      : Buat akaun SSH dan OpenVPN"
echo -e "* trial        : Buat akaun SSH dan OpenVPN sementara"
echo -e "* renew        : Extending SSH & OpenVPN Account Active Life"
echo -e "* deluser      : Delete akaun SSH dan OpenVPN"
echo -e "* member       : Lihat daftar Member akaun SSH dan OpenVPN"
echo -e "* delete       : Delete akaun SSH dan OpenVPN yang sudah expired"
echo -e "* autokill     : Set up Autokill SSH"
echo -e "* ceklim       : Tampilkan Multi Login SSH"
echo -e "* restart      : Mula ulang Dropbear, Webmin, Squid3,"
echo -e "                 OpenVPN dan SSH"
echo -e ""
echo -e "===========================-Wireguard-========================="
echo -e "* addwg        : Buat akaun Wireguard"
echo -e "* delwg        : Delete akaun Wireguard"
echo -e "* renewwg      : Renew akaun Wireguard"
echo -e "* wg show      : Cek tampilan Wireguard"
echo -e ""
echo -e "==========================-L2TP/IPSEC-========================="
echo -e "* addl2tp      : Creating L2TP / IPSEC Account"
echo -e "* dell2tp      : Deleting L2TP / IPSEC Account"
echo -e "* renewl2tp    : Extend L2TP / IPSEC Account"
echo -e ""
echo -e "=============================-PPTP-============================"
echo -e "* addpptp      : Create Account PPTP"
echo -e "* delpptp      : Delete PPTP Account"
echo -e "* renewpptp    : Extend PPTP Account"
echo -e ""
echo -e "=============================-SSTP-============================"
echo -e "* addsstp      : Create Account SSTP"
echo -e "* delsstp      : Delete SSTP Account"
echo -e "* renewsstp    : Extend SSTP Account"
echo -e ""
echo -e "=============================-SSR-============================="
echo -e "* addssr       : Buat akaun shadowsocks-R"
echo -e "* delssr       : Delete akaun shadowsocks-R"
echo -e "* renewssr     : Renew akaun shadowsocks-R"
echo -e "* ssr          : Tampilkan menu shadowsocks-R lainnya"
echo -e ""
echo -e "========================-Shadowsocks OBFS-====================="
echo -e "* addss        : Buat akaun shadowsocks"
echo -e "* delss        : Delete akaun shadowsocks"
echo -e "* renewss      : Renew akaun shadowsocks"
echo -e ""
echo -e "=============================-V2RAY-==========================="
echo -e "* addws        : Buat akaun vmess"
echo -e "* delws        : Delete akaun vmess"
echo -e "* renewws      : Renew akaun vmess"
echo -e "* certv2ray    : Renew certificate vmess"
echo -e ""
echo -e "=============================-VLESS-==========================="
echo -e "* addvless     : Buat akaun vless"
echo -e "* delvless     : Delete akaun vless"
echo -e "* renewvless   : Renew akaun vless"
echo -e ""
echo -e "=============================-Trojan-=========================="
echo -e "* addtr        : Buat akaun trojan"
echo -e "* deltr        : Delete akaun trojan"
echo -e "* renewtr      : Renew akaun trojan"
echo -e ""
echo -e "=============================-SYSTEM-=========================="
echo -e "* addhost      : Buat domain untuk VPS"
echo -e "* webmin       : Tampilkan menu webmin
echo -e "* ram          : Cek Penggunaan ram VPS"
echo -e "* reboot       : Reboot VPS"
echo -e "* speedtest    : Test kecepatan VPS"
echo -e "* info         : Informasi"
echo -e "* about        : Informasi script autossh"
echo -e ""
echo -e "==============================================================="
echo -e ""
